name: CI

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./...

  build-docker-image:
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before building the image
    if: startsWith(github.ref, 'refs/tags/v') # Only run on tag pushes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: 
            - scifferous/k8s-readiness-liveness-proxy:${{ github.event.release.tag_name }}
            - scifferous/k8s-readiness-liveness-proxy:latest
